apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default 
type: Opaque
data:
  # Replace `username` and `password` with your keys
  # Ensure these values are base64 encoded
  username: ZmFyb29xNzIy # base64 of 'username'
  password: ZmFyb29xQDY3MDA= # base64 of 'password'